# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Hsia
email: your-email@domain.com
description: >
  Kevin Hsia is a multimedia producer,
  DJ, & curator of Wine and Vinyl.
  He lives in Chicago, Illinois.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kevinhsia.com" # the base hostname & protocol for your site
twitter_username: kevinjhsia

# Build settings
markdown: kramdown

#Excludes
exclude: [
  "/node_modules",
  "/src",
  "/design",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "package.json",
  "LICENSE",
  "README.md"
  ]
